## Softmax Intuition

In [5]:
import numpy as np

def softmax(x):
    return np.exp(x) / np.sum(np.exp(x))

If there's a positive outlier, then softmax will give it most of the probability:

In [26]:
softmax(np.array([11, 2, 1, 0.5]))

array([  9.99803692e-01,   1.23385578e-04,   4.53910174e-05,
         2.75310437e-05])

If there's a negative outlier, it will be ignored, and the probability split among the remaining group:

In [23]:
softmax(np.array([2, 3, 2, -10]))

array([  2.11941282e-01,   5.76116135e-01,   2.11941282e-01,
         1.30221224e-06])

If values are close to each other, softmax will divived probability among them:

In [24]:
softmax(np.array([3, 2, 2.3, 1.8]))

array([ 0.46175322,  0.16986952,  0.22929986,  0.1390774 ])

In [27]:
softmax(np.array([11, 3, 1, -10]))

array([  9.99619282e-01,   3.35334911e-04,   4.53826452e-05,
         7.57967361e-10])