## Softmax Intuition

In [2]:
import numpy as np

def softmax(x):
    return np.exp(x) / np.sum(np.exp(x))

If there's a positive outlier, then softmax will give it most of the probability:

In [26]:
softmax(np.array([11, 2, 1, 0.5]))

array([  9.99803692e-01,   1.23385578e-04,   4.53910174e-05,
         2.75310437e-05])

If there's a negative outlier, it will be ignored, and the probability split among the remaining group:

In [23]:
softmax(np.array([2, 3, 2, -10]))

array([  2.11941282e-01,   5.76116135e-01,   2.11941282e-01,
         1.30221224e-06])

If values are close to each other, softmax will divived probability among them:

In [24]:
softmax(np.array([3, 2, 2.3, 1.8]))

array([ 0.46175322,  0.16986952,  0.22929986,  0.1390774 ])

In [1]:
softmax(np.array([11, 3, 1, -10]))

NameError: name 'softmax' is not defined

In [13]:
0.1 * np.random.rand(1, 5)

array([[ 0.02447547,  0.00602383,  0.0580481 ,  0.08923302,  0.09499426]])

In [52]:
w_xh = 0.078
w_hh = 0.024
in0 = w_xh * 1.0
print(in0)
h0 = np.tanh(in0)
print('h0 =', h0)

in1 = w_xh * 1.0 + h0 * w_hh
print('in1 =', in1)
h1 = np.tanh(in1)
print('h1 =', h1)

print('h1 * w_hh =', h1 * w_hh)

x2 = 2.0
print ('w_xh * x2 =', w_xh * x2)

print ('h1 * w_hh + w_xh * x2 =', h1 * w_hh + w_xh * x2)

h2 = np.tanh(h1 * w_hh + w_xh * x2)
print('h2 =', h2)

print('h2 * w_hh =', h2 * w_hh)

x3 = 3.0
print('w_xh * x3 =', w_xh * x3)

print('h2 * w_hh + w_xh * x3 =', h2 * w_hh + w_xh * x3)

h3 = np.tanh(h2 * w_hh + w_xh * x3)
print('h3 =', h3)

w_hy = 0.051
y = h3 * w_hy
print('y =', y)

x4 = 5
print('y - x4 =', y - x4)

print('(y - x4) ** 2 =', (y - x4) ** 2)

0.078
h0 = 0.0778422000109
in1 = 0.0798682128003
h1 = 0.0796988203869
h1 * w_hh = 0.00191277168929
w_xh * x2 = 0.156
h1 * w_hh + w_xh * x2 = 0.157912771689
h2 = 0.156613139136
h2 * w_hh = 0.00375871533927
w_xh * x3 = 0.23399999999999999
h2 * w_hh + w_xh * x3 = 0.237758715339
h3 = 0.233377648184
y = 0.0119022600574
y - x4 = -4.98809773994
(y - x4) ** 2 = 24.8811190632


In [25]:

print(h1 * w_xh)

0.00621680151531
